openapi: "3.0.0"
info:
  title: "Koa API"
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: "Greet the world"
      description: "Returns a greeting message"
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
